blog/urls.py
from django.conf.urls import url

from . import views
app_name= 'blog'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<post_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^menu/(?P<info_id>[0-9]+)/$', views.infol, name='infol'),
    url(r'^(?P<post_id>[0-9]+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<comment_id>[0-9]+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<comment_id>[0-9]+)/remove/$', views.comment_remove, name='comment_remove'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from __future__ import unicode_literals
from django.utils import timezone
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = RichTextUploadingField()
    image_for_preview = models.ImageField(upload_to='img')
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(default=timezone.now,blank=True, null=True)
    categoria = models.CharField(max_length=256, choices=[('Tramites', 'Tramites'), ('Info', 'Info'), ('Exp', 'Exp')], null=True)
    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class Infolink(models.Model):
    title = models.CharField(max_length=200)
    text = RichTextUploadingField()
    image_for_preview = models.ImageField(upload_to='img',blank=True)
    published_date = models.DateTimeField(default=timezone.now,blank=True, null=True)
    def publish(self):
        self.published_date = timezone.now()
        self.save()
    def __str__(self):
        return self.title

# FALTA PREVIEW IMAGE EN EL BIGCONTAINER Y EN EL TEMPLATE FALTA AGREGARLO TAMBIEN. ADEMAS FALTA METODO EN Bigc
# title equivale a un objeto post
# esto es el container, seleccionas en un dropdown menu el post que quieres ver de container
# como title es objeto ahora, title.title sera el titulo del objeto title, que sera un post. El titulo de un post
# el resto, de igual forma, title.text sera el atributo text del objecto post, que es el texto de un post
class Bigc(models.Model):
    title = models.ForeignKey('blog.Post')
    categoria = None
    text = None
    published_date = None
    image_preview = models.ImageField(default="img/default.png", upload_to='img', blank=False, help_text = "Imagenes deben ser de una resolucion: 600px ancho, 400px de alto. Esto para evitar inconvenientes")
    def publish(self):
        self.published_date = timezone.now()
        self.save()
    def __str__(self):
        return self.title.title
    def get_text(self):
        return self.title.text
    def get_categoria(self):
        return self.title.categoria

class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments')
    autor = models.CharField(max_length=200)
    texto = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.texto

blog/forms.py
from django import forms
from .models import Post, Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('autor', 'texto',)

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template import loader
from .models import Post
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Infolink
from .models import Bigc
from .forms import CommentForm
from django.shortcuts import redirect
from .models import Post, Comment
from django.contrib.auth.decorators import login_required


def index(request):
    biggy = Bigc.objects.all()
    infos = Infolink.objects.filter(published_date__lte=timezone.now()).order_by('published_date')[::-1]
    posts_list = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')[::-1]
    page = request.GET.get('page', 1)
    paginator = Paginator(posts_list, 6)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/index.html', {'posts': posts, 'infos': infos, 'biggy': biggy})
    # POSTS


def detail(request, post_id):
    biggy = Bigc.objects.all()
    infos = Infolink.objects.filter(published_date__lte=timezone.now()).order_by('published_date')[::-1]
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'blog/detail.html',{'post': post,'infos': infos, 'biggy': biggy})


def infol(request, info_id):
    biggy = Bigc.objects.all()
    info =get_object_or_404(Infolink, pk=info_id)
    infos = Infolink.objects.filter(published_date__lte=timezone.now()).order_by('published_date')[::-1]
    return render(request, 'blog/infol.html',{'info': info, 'infos': infos, 'biggy':biggy})


def add_comment_to_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:detail', post_id)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})


@login_required
def comment_approve(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.approve()
    return redirect('blog:detail', comment.post_id)


@login_required
def comment_remove(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.delete()
    return redirect('blog:detail', comment.post_id)

blog/templates/blog/add_comment_to_post.html
 <!-- FlatFy Theme - Andrea Galanti /-->
<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if IE 9]>    <html class="no-js ie9" lang="en"> <![endif]-->
<!--[if gt IE 9]><!--> <html> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="Flatfy Free Flat and Responsive HTML5 Template ">
    <meta name="author" content="">

    <title>Flatfy – Free Flat and Responsive HTML5 Template</title>
    {% load static %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'blog/css/bootstrap.min_detail.css' %}" rel="stylesheet">
 
    <!-- Custom Google Web Font -->
    <link href="{% static 'blog/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Arvo:400,700' rel='stylesheet' type='text/css'>
	
    <!-- Custom CSS-->
    <link href="{% static 'blog/css/general.css' %}" rel="stylesheet">
	
	 <!-- Owl-Carousel -->
    <link href="{% static 'blog/css/custom.css' %}" rel="stylesheet">
	<link href="{% static 'blog/css/owl.carousel.css' %}" rel="stylesheet">
    <link href="{% static 'blog/css/owl.theme.css' %}" rel="stylesheet">
	<link href="{% static 'blog/css/style.css' %}" rel="stylesheet">
	<link href="{% static 'blog/css/animate.css' %}" rel="stylesheet">
	
	<!-- Magnific Popup core CSS file -->
	<link rel="stylesheet" href="{% static 'blog/css/magnific-popup.css' %}"> 
	
	<script src="{% static 'blog/js/modernizr-2.8.3.min.js' %}"></script>  <!-- Modernizr /-->
	<!--[if IE 9]>
		<script src="js/PIE_IE9.js' %}"></script>
	<![endif]-->
	<!--[if lt IE 9]>
		<script src="js/PIE_IE678.js' %}"></script>
	<![endif]-->

	<!--[if lt IE 9]>
		<script src="js/html5shiv.js' %}"></script>
	<![endif]-->

</head>
<body>
        <div class="intro-header">
		<div class="col-xs-12 text-center abcen1">
			<a href="/"><h1 class="h1_home wow fadeIn" data-wow-delay="0.4s"><img src="{% static 'blog/img/logotop.png' %}" width="300" height="100"/></h1></a>
                <h3 class="h3_home wow fadeIn" data-wow-delay="0.6s">{% block content %}
                <h5>Nuevo comentario</h5>
                <form method="POST" class="post-form">{% csrf_token %}
                    {{ form.as_p }}

                        <ul class="list-inline intro-social-buttons">
                            <li>        <button type="submit" class="save btn btn-default">Enviar</button></form>{% endblock %}</h3>
				</li>
			</ul>
		</div>    
        <!-- /.container -->
		<div class="col-xs-12 text-center abcen wow fadeIn">
			<div class="button_down "> 
				<a class="imgcircle wow bounceInUp" data-wow-duration="1.5s"  href="#whatis"> <img class="img_scroll" src="static/blog/img/icon/circle.png" alt=""> </a>
			</div>
		</div>
    </div>

</body>
</html>

blog/templates/blog/backup-codecademy/index.html
<!DOCTYPE html>
<html>
<head>
  <title>Skillfair</title>
  <meta charset="utf-8"/>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" href="main.css">
</head>
  <section class="jumbotron">
    <div class="container">
      <div class="row text-center">
        <h2>David's Django Blog</h2>
        <h3>Python Developer</h3>
        <a class="btn btn-primary" href="#" role="button">See all</a>
      </div>
    </div>
  </section>
  <section class="container">
    <div class="row">
      <figure class="col-sm-6">
        <p>kitchen</p>
        <img scr="https://s3.amazonaws.com/codecademy-content/projects/make-a-website/lesson-4/kitchen.jpg
">
      </figure>
      <figure class="col-sm-6">
        <p>woodwork</p>
        <img src="https://s3.amazonaws.com/codecademy-content/projects/make-a-website/lesson-4/woodwork.jpg">
      </figure>
    </div>
    <div class="row">
      <figure class="col-sm-6"><p>gifts</p>
      <img src="https://s3.amazonaws.com/codecademy-content/projects/make-a-website/lesson-4/gifts.jpg">
      </figure>

      <figure class="col-sm-6">
        <p>antique</p>
        <img src="https://s3.amazonaws.com/codecademy-content/projects/make-a-website/lesson-4/antique.jpg">
      </figure>
      
    </div>
  </section>
  
 <footer class="container">
   <div class="row">
     <p class="col-sm-4">&copy; 2016 Skillfair</p>
     <ul class="col-sm-8">
<li class="col-sm-1">
  <img src="https://s3.amazonaws.com/codecademy-content/projects/make-a-website/lesson-4/twitter.svg">
</li>
<li class="col-sm-1">
  <img src="https://s3.amazonaws.com/codecademy-content/projects/make-a-website/lesson-4/facebook.svg">
</li>
<li class="col-sm-1">
  <img src="https://s3.amazonaws.com/codecademy-content/projects/make-a-website/lesson-4/instagram.svg">
</li>
<li class="col-md-1">
  <img src="https://s3.amazonaws.com/codecademy-content/projects/make-a-website/lesson-4/medium.svg">
</li>

     </ul>
   </div>
   </footer>
<body>
<header class="container">
 	<div class="row">
    <h1 class="col-sm-4">Skillfair</h1>
    <nav class="col-sm-8 text-right">
    	<p>newest</p>
    	<p>catalogue</p>
    	<p>contact</p>
    </nav>
  </div>
 </header>


</body>
</html>

blog/templates/blog/detail.html
 <!-- FlatFy Theme - Andrea Galanti /-->
<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if IE 9]>    <html class="no-js ie9" lang="en"> <![endif]-->
<!--[if gt IE 9]><!--> <html> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="Flatfy Free Flat and Responsive HTML5 Template ">
    <meta name="author" content="">

    <title>Flatfy – Free Flat and Responsive HTML5 Template</title>
    {% load static %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'blog/css/bootstrap.min_detail.css' %}" rel="stylesheet">
 
    <!-- Custom Google Web Font -->
    <link href="{% static 'blog/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Arvo:400,700' rel='stylesheet' type='text/css'>
	
    <!-- Custom CSS-->
    <link href="{% static 'blog/css/general.css' %}" rel="stylesheet">
	
	 <!-- Owl-Carousel -->
    <link href="{% static 'blog/css/custom.css' %}" rel="stylesheet">
	<link href="{% static 'blog/css/owl.carousel.css' %}" rel="stylesheet">
    <link href="{% static 'blog/css/owl.theme.css' %}" rel="stylesheet">
	<link href="{% static 'blog/css/style.css' %}" rel="stylesheet">
	<link href="{% static 'blog/css/animate.css' %}" rel="stylesheet">
	
	<!-- Magnific Popup core CSS file -->
	<link rel="stylesheet" href="{% static 'blog/css/magnific-popup.css' %}"> 
	
	<script src="{% static 'blog/js/modernizr-2.8.3.min.js' %}"></script>  <!-- Modernizr /-->
	<!--[if IE 9]>
		<script src="js/PIE_IE9.js' %}"></script>
	<![endif]-->
	<!--[if lt IE 9]>
		<script src="js/PIE_IE678.js' %}"></script>
	<![endif]-->

	<!--[if lt IE 9]>
		<script src="js/html5shiv.js' %}"></script>
	<![endif]-->

</head>

<body id="home">

	<!-- Preloader -->
	<div id="preloader">
		<div id="status"></div>
	</div>
	
	<!-- FullScreen -->
    <div class="intro-header">
		<div class="col-xs-12 text-center abcen1">
			<a href="/"><h1 class="h1_home wow fadeIn" data-wow-delay="0.4s"><img src="{% static 'blog/img/logotop.png' %}" width="300" height="100"/></h1></a>
			<h3 class="h3_home wow fadeIn" data-wow-delay="0.6s">...el cono sur.</h3>
			<ul class="list-inline intro-social-buttons">
				<li><a href="https://twitter.com/galantiandrea" class="btn  btn-lg mybutton_cyano wow fadeIn" data-wow-delay="0.8s"><span class="network-name">Twitter</span></a>
				</li>
				<li id="download" ><a href="#downloadlink" class="btn  btn-lg mybutton_standard wow swing wow fadeIn" data-wow-delay="1.2s"><span class="network-name">Free Download</span></a>
				</li>
			</ul>
		</div>    
        <!-- /.container -->
		<div class="col-xs-12 text-center abcen wow fadeIn">
			<div class="button_down "> 
				<a class="imgcircle wow bounceInUp" data-wow-duration="1.5s"  href="#whatis"> <img class="img_scroll" src="{% static 'blog/img/icon/circle.png' %}" alt=""> </a>
			</div>
		</div>
    </div>
	
	<!-- NavBar-->
	<nav class="navbar-default" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="/">DelNorteAlSur</a>
			</div>

			<div class="collapse navbar-collapse navbar-right navbar-ex1-collapse">
				<ul class="nav navbar-nav">
					{% for info in infos %}
					<li class="menuItem"><a href="{% url 'blog:infol' info.id %}">{{ info.title }}</a></li>
                    {% endfor %}
				</ul>
			</div>
		   
		</div>
	</nav> 
	
	<!-- What is -->
	<div id="whatis" class="content-section-b" style="border-top: 0">
		<div class="container">

			<div class="col-md-6 col-md-offset-3 text-center wrap_title">
				<h2></h2>
				<p class="lead" style="margin-top:0"></p>
				
			</div>
			
			<div class="row">
				<div class="col-sm-4 wow fadeInDown text-center">
				  <img class="rotate" src="{{ MEDIA_URL }}{{ post.image_for_preview.url }}" alt="Generic placeholder image" width="100px" height="100px">
				  <a href="{% url 'blog:detail' post.id %}"><h3>{{ post.title }}</h3></a>
                    <p class="lead">{{ post.text|safe|linebreaksbr }}</p></div>
                <div class="col-sm-6 wow fadeInLeftBig animated animated">
{% for comment in post.comments.all %}
    {% if user.is_authenticated or comment.approved_comment %}
    <div class="comment">
        <div class="date"><hr>
            {{ comment.created_date }}
            {% if not comment.approved_comment %}
                <a class="btn btn-default" href="{% url 'blog:comment_remove' comment.id %}"><span class="glyphicon glyphicon-remove"></span></a>
                <a class="btn btn-default" href="{% url 'blog:comment_approve' comment.id %}"><span class="glyphicon glyphicon-ok"></span></a>
            {% endif %}
        </div>
        <strong>{{ comment.autor }}</strong>
        <p>{{ comment.texto|linebreaks }}</p>
    </div><hr>
    {% endif %}
{% empty %}
    <p>No comments here yet :(</p>
{% endfor %}
                <a class="btn btn-default" href="{% url 'blog:add_comment_to_post' post.id %}">Agregar commentario</a>
				  <!-- <p><a class="btn btn-embossed btn-primary view" role="button">View Details</a></p> -->
				</div><!-- /.col-lg-4 -->
				
				
			</div><!-- /.row -->
				
		</div>
    </div>
	<!-- Use it -->
    {% for ele in biggy %}
    <div id ="useit" class="content-section-a">

        <div class="container">
			
            <div class="row">
			
				<div class="col-sm-6 pull-right wow fadeInRightBig">
                    <img class="img-responsive " src="{{ MEDIA_URL }}{{ ele.image_preview.url }}" alt="" width="600px" height="400px">
                </div>
                <div class="col-sm-6 wow fadeInLeftBig"  data-animation-delay="200">   
                    <h3 class="section-heading">{{ ele.title }}</h3>
					<div class="sub-title lead3">{{ ele.get_categoria }}</div>
                    <p class="lead">
						{{ ele.get_text|safe|linebreaksbr|truncatechars:145 }}
					</p>

					 <p><a class="btn btn-embossed btn-primary" href="#" role="button">View Details</a> 
					 <a class="btn btn-embossed btn-info" href="#" role="button">Visit Website</a></p>
				</div>   
            </div>
        </div>
        <!-- /.container -->
    </div>{% endfor %}

	<!-- Screenshot
	<div id="screen" class="content-section-b">
        <div class="container">
          <div class="row" >
			 <div class="col-md-6 col-md-offset-3 text-center wrap_title ">
				<h2>Screen App</h2>
				<p class="lead" style="margin-top:0">A special thanks to Death.</p>
			 </div>
		  </div>
		    <div class="row wow bounceInUp" >
              <div id="owl-demo" class="owl-carousel">
				
				<a href="{% static 'blog/img/slide/1.png' %}" class="image-link">
					<div class="item">
						<img  class="img-responsive img-rounded" src="{% static 'blog/img/slide/1.png' %}" alt="Owl Image">
					</div>
				</a>
				
               <a href="{% static 'blog/img/slide/2.png' %}" class="image-link">
					<div class="item">
						<img  class="img-responsive img-rounded" src="{% static 'blog/img/slide/2.png' %}" alt="Owl Image">
					</div>
				</a>
				
				<a href="{% static 'blog/img/slide/3.png' %}" class="image-link">
					<div class="item">
						<img  class="img-responsive img-rounded" src="{% static 'blog/img/slide/3.png' %}" alt="Owl Image">
					</div>
				</a>
				
				<a href="{% static 'blog/img/slide/1.png' %}" class="image-link">
					<div class="item">
						<img  class="img-responsive img-rounded" src="{% static 'blog/img/slide/1.png' %}" alt="Owl Image">
					</div>
				</a>
				
               <a href="{% static 'blog/img/slide/2.png' %}" class="image-link">
					<div class="item">
						<img  class="img-responsive img-rounded" src="{% static 'blog/img/slide/2.png' %}" alt="Owl Image">
					</div>
				</a>
				
				<a href="{% static 'blog/img/slide/3.png' %}" class="image-link">
					<div class="item">
						<img  class="img-responsive img-rounded" src="{% static 'blog/img/slide/3.png' %}" alt="Owl Image">
					</div>
				</a>
              </div>       
          </div>
        </div>


	</div>	 //-->
	
	
	<!-- Credits -->
	
	<!-- Banner Download -->
	
	<!-- Contact -->
 <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-7">
            			<hr class="featurette-divider hidden-lg">
				<div class="col-md-5 col-md-push-1 address">
					<address>
					<h3>Ubicación</h3>
					<p class="lead"><a href="https://www.google.com/maps/preview?ie=UTF-8&q=The+Pentagon&fb=1&gl=us&hq=1400+Defense+Pentagon+Washington,+DC+20301-1400&cid=12647181945379443503&ei=qmYfU4H8LoL2oATa0IHIBg&ved=0CKwBEPwSMAo&safe=on">CABA<br>
					Argentina</a><br>
					info@vitacoradelsur.com</p>
					</address>

					<h3>Social</h3>
					<li class="social"> 
					<a href="https://www.facebook.com/VitacoraDelSur"><i class="fa fa-facebook-square fa-size"> </i></a>
					<a href="https://twitter.com/vitacoradelsur"><i class="fa  fa-twitter-square fa-size"> </i> </a> 
					<a href="#"><i class="fa fa-google-plus-square fa-size"> </i></a>
					<a href="#"><i class="fa fa-flickr fa-size"> </i> </a>
                    </li></div>   
          </div> <!-- /col-xs-7 -->

          <div class="col-md-5">
            <div class="footer-banner">
              <h3 class="footer-title">VitácoraDelSur</h3>
              <ul>
                <li>Contacto</li>
                <li>Acerca de nosotros</li>
                <li>Servicios</li>
              </ul>
              Developer: <a href="davidpenott.com" target="_blank">davidpenott.com</a><br>
                <br>
                                    <!-- LICENSE -->
			<a rel="cc:attributionURL" href="http://www.andreagalanti.it/flatfy"
		   property="dc:title">Flatfy Theme </a> by
		   <a rel="dc:creator" href="http://www.andreagalanti.it"
		   property="cc:attributionName">Andrea Galanti is licensed to the public under the   <a rel="license"
		   href="http://creativecommons.org/licenses/by-nc/3.0/it/deed.it">Creative Commons Attribution 3.0 License - NOT COMMERCIAL</a> </a>	   
          </div> <!-- /col-xs-7 -->
            </div>
          </div>
        </div>
      </div>
    </footer>


    <!-- JavaScript -->
    <script src="{% static 'blog/js/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.js' %}"></script>
	<script src="{% static 'blog/js/owl.carousel.js' %}"></script>
	<script src="{% static 'blog/js/script.js' %}"></script>
	<!-- StikyMenu -->
	<script src="{% static 'blog/js/stickUp.min.js' %}"></script>
	<script type="text/javascript">
	  jQuery(function($) {
		$(document).ready( function() {
		  $('.navbar-default').stickUp();
		  
		});
	  });
	
	</script>
	<!-- Smoothscroll -->
	<script type="text/javascript" src="{% static 'blog/js/jquery.corner.js' %}"></script> 
	<script src="{% static 'blog/js/wow.min.js' %}"></script>
	<script>
	 new WOW().init();
	</script>
	<script src="{% static 'blog/js/classie.js' %}"></script>
	<script src="{% static 'blog/js/uiMorphingButton_inflow.js' %}"></script>
	<!-- Magnific Popup core JS file -->
	<script src="{% static 'blog/js/jquery.magnific-popup.js' %}"></script> 
</body>

</html>